# Stage 1: Build
FROM node:22-alpine AS builder

WORKDIR /app

ARG VITE_APP_SERVER_URL
ARG VITE_TURNSTILE_SITE_KEY

ENV VITE_APP_SERVER_URL=$VITE_APP_SERVER_URL
ENV VITE_TURNSTILE_SITE_KEY=$VITE_TURNSTILE_SITE_KEY

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Release
FROM nginxproxy/nginx-proxy:1.5

WORKDIR /app

COPY nginx.tmpl /app/nginx.tmpl

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80