---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
  labels:
    app: backend
data:
  SALT_ROUNDS: "10"
  DB_NAME: ${DB_NAME}
  NODE_ENV: "development"
  REFRESH_TOKEN_TTL: "2592000"
  CLIENT_BASE_URL: ${CLIENT_BASE_URL}
  ACCESS_JWT_SECRET: ${ACCESS_JWT_SECRET}
