---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: backend
type: Opaque
data:
  MONGO_URI: ${BASE64_MONGO_URI}
  RESEND_API_KEY: ${BASE64_RESEND_API_KEY}
  TURNSTILE_SECRET_KEY: ${BASE64_TURNSTILE_SECRET_KEY}
  CONTACT_RECEIVER_EMAIL: ${BASE64_CONTACT_RECEIVER_EMAIL}
